"""empty message

Revision ID: 1f8616a00c6e
Revises: 764d968f88ee
Create Date: 2024-11-05 14:24:15.016588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f8616a00c6e"
down_revision: Union[str, None] = "764d968f88ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("items_app_id_fkey", "items", type_="foreignkey")
    op.create_foreign_key(None, "items", "apps", ["app_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("steps_check_list_entity_id_fkey", "steps", type_="foreignkey")
    op.create_foreign_key(
        None, "steps", "items", ["check_list_entity_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("ticks_check_list_id_fkey", "ticks", type_="foreignkey")
    op.drop_constraint("ticks_clothes_id_fkey", "ticks", type_="foreignkey")
    op.create_foreign_key(
        None, "ticks", "clothes", ["clothes_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "ticks", "items", ["check_list_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ticks", type_="foreignkey")
    op.drop_constraint(None, "ticks", type_="foreignkey")
    op.create_foreign_key(
        "ticks_clothes_id_fkey", "ticks", "clothes", ["clothes_id"], ["id"]
    )
    op.create_foreign_key(
        "ticks_check_list_id_fkey", "ticks", "items", ["check_list_id"], ["id"]
    )
    op.drop_constraint(None, "steps", type_="foreignkey")
    op.create_foreign_key(
        "steps_check_list_entity_id_fkey",
        "steps",
        "items",
        ["check_list_entity_id"],
        ["id"],
    )
    op.drop_constraint(None, "items", type_="foreignkey")
    op.create_foreign_key("items_app_id_fkey", "items", "apps", ["app_id"], ["id"])
    # ### end Alembic commands ###
