"""empty message

Revision ID: 7e7beb04c6c3
Revises: 
Create Date: 2024-10-30 14:42:53.879390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e7beb04c6c3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apps",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "clothes_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clothes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_male", sa.Boolean(), nullable=True),
        sa.Column("is_female", sa.Boolean(), nullable=True),
        sa.Column("is_3_days", sa.Boolean(), nullable=True),
        sa.Column("is_7_days", sa.Boolean(), nullable=True),
        sa.Column("is_14_days", sa.Boolean(), nullable=True),
        sa.Column("is_domestic", sa.Boolean(), nullable=True),
        sa.Column("is_international", sa.Boolean(), nullable=True),
        sa.Column("is_warm_weather", sa.Boolean(), nullable=True),
        sa.Column("is_cold_weather", sa.Boolean(), nullable=True),
        sa.Column("is_skiing", sa.Boolean(), nullable=True),
        sa.Column("is_beach", sa.Boolean(), nullable=True),
        sa.Column("is_business_trip", sa.Boolean(), nullable=True),
        sa.Column("is_camping", sa.Boolean(), nullable=True),
        sa.Column("id_category", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_category"],
            ["clothes_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clothes_id"), "clothes", ["id"], unique=False)
    op.create_table(
        "items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("app_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["apps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sex", sa.String(), nullable=True),
        sa.Column("days", sa.Integer(), nullable=True),
        sa.Column("destination", sa.String(), nullable=True),
        sa.Column("weather", sa.String(), nullable=True),
        sa.Column("trip_type", sa.String(), nullable=True),
        sa.Column("check_list_entity_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["check_list_entity_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("check_list_id", sa.String(), nullable=True),
        sa.Column("clothes_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["check_list_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clothes_id"],
            ["clothes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticks_id"), "ticks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticks_id"), table_name="ticks")
    op.drop_table("ticks")
    op.drop_table("steps")
    op.drop_table("items")
    op.drop_index(op.f("ix_clothes_id"), table_name="clothes")
    op.drop_table("clothes")
    op.drop_table("clothes_category")
    op.drop_table("apps")
    # ### end Alembic commands ###
