"""empty message

Revision ID: a12802c689e2
Revises: ab83b2e4e0fe
Create Date: 2024-11-07 23:25:14.069537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a12802c689e2"
down_revision: Union[str, None] = "ab83b2e4e0fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=True))
    op.drop_constraint("users_role_fkey", "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "roles", ["role_id"], ["id"])
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key("users_role_fkey", "users", "roles", ["role"], ["id"])
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###
