"""empty message

Revision ID: 68960b908ae1
Revises: 
Create Date: 2024-10-17 19:13:20.610962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68960b908ae1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_male', sa.Boolean(), nullable=True),
    sa.Column('is_female', sa.Boolean(), nullable=True),
    sa.Column('is_3_days', sa.Boolean(), nullable=True),
    sa.Column('is_7_days', sa.Boolean(), nullable=True),
    sa.Column('is_14_days', sa.Boolean(), nullable=True),
    sa.Column('is_domestic', sa.Boolean(), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=True),
    sa.Column('is_warm_weather', sa.Boolean(), nullable=True),
    sa.Column('is_cold_weather', sa.Boolean(), nullable=True),
    sa.Column('is_skiing', sa.Boolean(), nullable=True),
    sa.Column('is_beach', sa.Boolean(), nullable=True),
    sa.Column('is_business_trip', sa.Boolean(), nullable=True),
    sa.Column('is_camping', sa.Boolean(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['clothes_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothes_id'), 'clothes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothes_id'), table_name='clothes')
    op.drop_table('clothes')
    op.drop_table('clothes_category')
    # ### end Alembic commands ###
