"""empty message

Revision ID: c5266934b4bc
Revises: 
Create Date: 2024-10-01 11:55:57.404612

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5266934b4bc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sex", sa.String(), nullable=True),
        sa.Column("days", sa.Integer(), nullable=True),
        sa.Column("destination", sa.String(), nullable=True),
        sa.Column("weather", sa.String(), nullable=True),
        sa.Column("trip_type", sa.String(), nullable=True),
        sa.Column("check_list_entity_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["check_list_entity_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "items",
        "app_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "items",
        "app_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_table("steps")
    # ### end Alembic commands ###
