"""empty message

Revision ID: e998b993134c
Revises: 68960b908ae1
Create Date: 2024-10-23 15:05:03.651818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e998b993134c'
down_revision: Union[str, None] = '68960b908ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_list_id', sa.String(), nullable=True),
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_list_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticks_id'), 'ticks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticks_id'), table_name='ticks')
    op.drop_table('ticks')
    # ### end Alembic commands ###
