on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: node telegram-bot.js
      - name: TG_TOKEN
        env:
          GITHUB_CONTEXT: ${{ secrets.TG_BOT_TOKEN }}
        run: echo token ${{ secrets.TG_BOT_TOKEN }}
